[package]
name = "css-typing-gen"
description = "CSS Typing animation generator"
version = "0.1.6"
edition = "2021"
repository = "https://github.com/ayes-web/css-typing-gen"

[lib]
crate-type = ["cdylib"]

[profile.release]
lto = true

[dependencies]
wasm-bindgen = { version = "0.2.83" }
gloo = "0.8.0"
chrono = "0.4.22"
console_error_panic_hook = "0.1.7"
js-sys = "0.3.60"

[dependencies.web-sys]
version = "0.3.60"
features = [
  'Document',
  'Element',
  'Event',
  'EventTarget',
  'HtmlInputElement',
  'HtmlButtonElement',
  'HtmlStyleElement',
  'HtmlDivElement',
]
